# Generated by Django 4.0.3 on 2022-03-04 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0, message='This number cannot be less than 0'))),
                ('rented', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0, message='This number cannot be less than 0'))),
            ],
        ),
    ]
